[package]
name = "isharepy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "isharepy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
ishare = {path = "../"}
ahash = "*"
numpy = "0.19.0"
